package(
    default_visibility = [
        "//keras:__subpackages__",
    ],
    licenses = ["notice"],
)

filegroup(
    name = "all_py_srcs",
    srcs = glob(["*.py"]),
    visibility = ["//keras/google/private_tf_api_test:__pkg__"],
)

# tf_py_test(
#     name = "callbacks_test",
#     size = "large",
#     srcs = ["callbacks_test.py"],
#     python_version = "PY3",
#     deps = [
#         "//:expect_absl_installed",
#         "//:expect_numpy_installed",
#         "//:expect_tensorflow_installed",
#         "//keras",
#         "//keras/api:keras_api",
#         "//keras:combinations",
#     ],
# )

# tf_py_test(
#     name = "correctness_test",
#     size = "large",
#     srcs = ["correctness_test.py"],
#     python_version = "PY3",
#     deps = [
#         "//:expect_absl_installed",
#         "//:expect_numpy_installed",
#         "//:expect_tensorflow_installed",
#         "//keras",
#         "//keras/api:keras_api",
#         "//keras:combinations",
#     ],
# )

# tf_py_test(
#     name = "deferred_sequential_test",
#     size = "large",
#     srcs = ["deferred_sequential_test.py"],
#     python_version = "PY3",
#     deps = [
#         "//:expect_absl_installed",
#         "//:expect_numpy_installed",
#         "//:expect_tensorflow_installed",
#         "//keras",
#         "//keras/api:keras_api",
#         "//keras:combinations",
#     ],
# )

# tf_py_test(
#     name = "functional_test",
#     size = "large",
#     srcs = ["functional_test.py"],
#     python_version = "PY3",
#     deps = [
#         "//:expect_absl_installed",
#         "//:expect_numpy_installed",
#         "//:expect_tensorflow_installed",
#         "//keras",
#         "//keras/api:keras_api",
#         "//keras:combinations",
#     ],
# )

# tf_py_test(
#     name = "metrics_correctness_test",
#     size = "large",
#     srcs = ["metrics_correctness_test.py"],
#     python_version = "PY3",
#     deps = [
#         "//:expect_absl_installed",
#         "//:expect_numpy_installed",
#         "//:expect_tensorflow_installed",
#         "//keras",
#         "//keras/api:keras_api",
#         "//keras:combinations",
#     ],
# )

# tf_py_test(
#     name = "metrics_test",
#     size = "large",
#     srcs = ["metrics_test.py"],
#     python_version = "PY3",
#     deps = [
#         "//:expect_absl_installed",
#         "//:expect_numpy_installed",
#         "//:expect_tensorflow_installed",
#         "//keras",
#         "//keras/api:keras_api",
#         "//keras:combinations",
#     ],
# )

# tf_py_test(
#     name = "sequential_test",
#     size = "large",
#     srcs = ["sequential_test.py"],
#     python_version = "PY3",
#     deps = [
#         "//:expect_absl_installed",
#         "//:expect_numpy_installed",
#         "//:expect_tensorflow_installed",
#         "//keras",
#         "//keras/api:keras_api",
#         "//keras:combinations",
#     ],
# )

# tf_py_test(
#     name = "training_test",
#     size = "large",
#     srcs = ["training_test.py"],
#     python_version = "PY3",
#     shard_count = 20,
#     deps = [
#         "//:expect_absl_installed",
#         "//:expect_numpy_installed",
#         "//:expect_tensorflow_installed",
#         "//keras",
#         "//keras/api:keras_api",
#         "//keras:combinations",
#     ],
# )
